### ISSUE TITLE
Willing to take over maintenance & hosting

### ISSUE THREAD

**Issue by GeekRuthie** [GeekRuthie/perl101#15]
I'm willing to take over the maintenance and hosting of the site--I didn't even know it existed, or I'd have been sending people here for *years*!

Some things I'd like to do with it:

* Better advertising; our community needs to know more about this great resource
* Engage members of the Perl 6 community to get content for that language
* Make the site more interactive--feedback, maybe discussion space, maybe even an interactive code-runner of some sort so users can "play," like JSFiddle.
* Make sure that all the information conforms to Modern Perl usage
* Enhance the link page to add more pointers to other Perl resources
* Some sections on popular modules/frameworks, like TT, DBIC, Dancer, Mojo, Mouse/Moo/Moose, Catalyst

All of this may require moving to some sort of CMS, or some more-involved programming. My current gig is doing a massive amount of DBIx::Class/Dancer2/TT work, so that doesn't worry me much, if that's where it needs to go.

This is a fantastic--but under-utilized--resource!

**Comment by GeekRuthie** [comment]
...and I hit <enter> and github thought I was done.  I'm not.

I'm willing to take over the maintenance and hosting of the site--I didn't even know it existed, or I'd have been sending people here for *years*!

Some things I'd like to do with it:

* Better advertising; our community needs to know more about this great resource
* Engage members of the Perl 6 community to get content for that language
* Make the site more interactive--feedback, maybe discussion space, maybe even an interactive code-runner of some sort so users can "play," like JSFiddle.
* Make sure that all the information conforms to Modern Perl usage
* Enhance the link page to add more pointers to other Perl resources

All of this may require moving to some sort of CMS, or some more-involved programming. My current gig is doing a massive amount of DBIx::Class/Dancer2/TT work, so that doesn't worry me much, if that's where it needs to go.

This is a fantastic--but under-utilized--resource!

**Comment by GeekRuthie** [comment]
Another thing for that bullet list:

* Some sections on popular modules/frameworks, like TT, DBIC, Dancer, Mojo, Mouse/Moo/Moose, Catalyst

**Comment by petdance** [comment]
Thanks for the quick response.  I'll get back to you and anyone else who responds in a week or so, to give others a chance to chime in.

**Comment by lizmat** [comment]
I was going to offer to take over the domain to prevent it from expiring.  However, if @GeekRuthie is going to take over this service, I'd be willing to provide Perl 6 related content.  As wth @GeekRuthie, I didn't know this resource existed!

**Comment by petdance** [comment]
Looks like part of what needs to happen is getting more attention pointing at it. :-)

I'm very happy to see so much positive response to this.

**Comment by GeekRuthie** [comment]
That bullet list up there isn't precisely in order-of-doing, of course; I'll probably hack on things a while structurally, before beefing up the volume level on it.  But yeah, more people need to know about this--I'll definitely do a lightning talk about it at TPCiP this summer!

I do like the idea of using POD for the "teaching" pages; that makes it nice for suggestions of new/updated content--just send a pull request! Some of the more-dynamic stuff, like the link pages, I may work around other ways, in order to get *other* features I'd like to see.  Given my current bias toward Dancer2 (with what I do every day for $WORK), I'm thinking of making an application out of it.

**Comment by petdance** [comment]
My only caveat to that is that it's easy to get sucked into the coding part and let the content fall by the wayside.  On the minus side, `podium` is long-neglected and may not even build any more.

**Comment by GeekRuthie** [comment]
My coding goal here is to make it so that, to add new content, just add a new POD, and the app does the rest, automagically.  I'm already doing something similar elsewhere, so a lot of this isn't new code for me.  I could switch this to a substantially-similar Dancer2 application in a week or two of spare time, I suspect, then start adding new features and content.

**Comment by tmetro** [comment]
The Perl Shop has an interest in sponsoring perl101.org in the form of paying for the domain and hosting. But to be up front, our interest in this site would be to increase our ability to market services to Perl novices. (The theory being that some percentage of people who are looking for introductory Perl information will be people charged with maintaining a legacy application, and if they decide they're in over their head, we'd like them to reach out to us.) Thus we'd want to have our branding visible on the site in some fashion (banner ad or some such).

That, of course, doesn't mean we're not also interested in making it a good community resource. And we're happy to work cooperatively with others on developing the content.

The biggest question we've raised when considering creating an introductory site is how will the site be different from the existing tutorial sites for Perl? We're a relatively small community with limited resources, and I think it would be contrary to our collective interests to have a bunch of Perl tutorial sites that compete, if there isn't a clear reason why someone chooses one over the other.

It's not like there aren't already decent Perl tutorial sites. To list a few:
https://perlmaven.com/perl-tutorial (probably the best known tutorial site)
http://mvp.kablamo.org/ (fairly similar to perl101.org)
http://perl-begin.org/
https://www.learn-perl.org/

Even a meta-site to list and rate the other tutorials already exists:
http://perl-tutorial.org/

So an argument could be made that the best way to serve the community would be to redirect the perl101.org traffic to your pick of the above, and then invest your time contributing to that existing site.


GeekRuthie wrote:
> Some things I'd like to do with it:
> * Better advertising; our community needs to know more about this great resource

Agreed. And that's true for Perl tutorial information in general.

We've been making it a practice to post at least one tutorial item to social media weekly (Tuesdays), and that also gets included in our newsletter.

If the how-tos are already well covered by other sites, one take on perl101.org is that it could be a promotional vehicle for existing Perl tutorial content. In this scenario it would be a blog that curates content - be that blog postings, YouTube videos, e-books, etc. - as long as it fits some criteria for being introductory content.

This curated content could be distributed in the usual ways - blog, RSS, social media feeds, and newsletter. And the curation could be done by multiple people.

Another approach might be to repackage the existing material into an online course which could be parceled out in lessons via email. The user could pick whether they want a "crash course" and receive a lesson every day, or a leisurely pace of a lesson per week. There could be interactive or gameified elements on the site to motivate the user to complete the lessons and stay on track. (Although I suspect building that functionality would be reinventing a wheel already covered by the many online course sites. As above, you have to wonder if the community would be better off investing its time into creating course material for services like khanacademy.org or commercial course sites. Build one high-quality tutorial, and distribute it for free on all the course sites that will take it.)


> * Make the site more interactive--feedback, maybe discussion space, maybe even an interactive code-runner of some sort so users can "play," like JSFiddle.
That sounds good in theory, but that would also be adding a lot of code that needs to be maintained. Having a discussion space that is "safe" for novice users would be good, but is that hard to find elsewhere?

https://perlbanjo.com/ was just announced as an interactive code-runner.

It might be best to follow the tradition of search.cpan.org and metacpan.org and integrate 3rd party services, rather than building all the functionality into the site.

Ultimately you want a site that minimizes maintenance effort if you want the site to be sustainable in the long run.


> All of this may require moving to some sort of CMS...
Or maybe revisiting some old tech, like a wiki...Twiki is still a thing and is built with Perl. That's presuming the vision for perl101.org includes user contributed content and the spam can be managed. (As much as a pull request is an appealing mechanism for us experienced developers, I'm not sure it is the right approach for a site where you might want contributions from novice developers.)

The other points mentioned, like making sure the content adhere to Modern Perl, and having a Perl 6 version, all sounds fine, but comes into play once the larger vision for the site is determined.

 -Tom

**Comment by petdance** [comment]
All good points, thank you, @tmetro.

@GeekRuthie can you please drop me an email at andy@petdance.com and let's talk about how we can get this transfer started?

**Comment by GeekRuthie** [comment]
@tmetro has given us a lot to unpack here, and I don't actually disagree with much of it. Deciding the best way to take the site is definitely a longer-term, collaborative proposition, not one to be handled for all time in this space. But I'd like to address the overall vision somewhat, and see where that takes the discussion.

The core piece of my vision is of a site neutral to the semi-political shenanigans that embroils our community from time to time--I'm not looking to fight out the differences or relative value between Perl and PHP, or Perl 5 vs Perl 6, or Catalyst vs Moose, or this community member vs that one. If someone submits content that spends time in those sorts of arguments, my intent is to edit the content (or require the submitter to) to conform to the goal:  Teach Me The Thing. That may result in content that is of little to no use to me, personally, turning up--I'm okay with that. At the moment, given what I do, I'm a Dancer2/DBIx::Class enthusiast, and am happy to lay out some content on that. But I'd welcome tutorials on other frameworks and modules, as well, by whatever method we develop for getting that content, so long as it meets that single goal:  Teach Me The Thing.

A collateral part of that mindset, in my mind, is that the site should be forever free of commercial influence. I'm not knocking The Perl Shop, or any other of our commercial participants in the community, at all--indeed, I *am* one, coding for Clearbuilt. That is why I've offered to stand the site up myself, paying for it myself. I might put up a donations button to help cover hosting costs, but those have gotten so cheap that it's an expense I just don't mind bearing without any financial assistance, at least with the load that @petdance mentioned in his PerlBuzz notice about this need, and a fair bit more beyond that.  I welcome collaboration and contribution to the content, but my own sense is that there should never be a quid-pro-quo for that: do it for the good of the community, and no other reason, or sit this one out.

Implementation ideas--

I spitballed a few ideas in my original note, none of which, of course, are carved in stone. @tmetro has thrown a few more out there, and there aren't any of them that are "bad." Interestingly, out of the other Perl tutorial sites, only Perl Maven was one I had heard of before, and that raises the flag even higher to me that we need to plug our tutorial content even harder, as a community.  I like the idea of cross-pollination of content with other sites, a lot, but the idea of merely redirecting this URL to somewhere else does not appeal as much.

As someone who's spent a lot of time teaching and training over the course of my career, I understand fully that learners have different styles, and a piece of content that works as a teaching tool for one student, may not for another.  That's part of why cross-pollinating content to/from other sites appeals to me, in part--by the TIMTOWTDI prinicple, there's not one way to learn Perl. Indeed, I think there's a place for non-textual content, too, videos and slide decks and audio tracks, any one of which may hit a learner in the spot they need to increase their understanding. My hope--in the longer term--is to engage content creators and a team of curators to help put together not just a small set of tutorials as the site is currently implemented, but a clearing-house for quality beginner-level content, both on-site and off. How we organize and structure that content is a matter for a (much) longer conversation.

I saw perlbanjo had popped up the other day, and marveled at the timeliness of it. I've also looked briefly at the CodeMirror tools that are used in a few places, and thought that might be useful as well.

I have not spent a *lot* of time on implementation details on any of this, yet, mostly sitting and waiting to see what the discussion looked like, and which decisions @petdance makes.

(....and while I was typing it, he commented, so I'll stop clattering away on this, and send him an email as requested. )

**Comment by petdance** [comment]
Amen about just paying the costs out of pocket.  $10/year for domain, and hanging another subdomain off an Nginx instance is no big deal.

**Comment by GeekRuthie** [comment]
> Amen about just paying the costs out of pocket. $10/year for domain, and hanging another subdomain off an Nginx instance is no big deal.

Exactly; I've already *got* hosting, for my own domains, and standing up another one just won't cost me much of anything, even if the traffic level goes up quite a bit. My current hosting is overkill for my needs, and the provider has some lovely incremental plans that will let me crank it up as needed.

**Comment by petdance** [comment]
One thing I want to point about my original vision for perl101, which of course you're under no obligation to follow:  My vision for the site wasn't that it would be a place for people to learn Perl from scratch.  Instead, it was a collection of information like the tagline says: "Things every Perl programmer should know."

It came about from years of reading StackOverflow and seeing people who were just learning Perl, had learned just enough syntax to start creating code, but who didn't know what they didn't know.

The best example I have is on http://perl101.org/regexes.html where I have a section on "Don't use capture variables without checking that the match succeeded."  Consider the code:

    my $str = 'Perl 101 rocks.';
    $str =~ /(\d+)/;
    my $number = $1;

To the beginner Perl programmer, that looks just fine.  The danger of not having checked that the regex matched isn't obvious, because the code seems to work.  I wanted to fill the pages of perl101.org with stuff like that, where someone who kinda knew Perl a little would find out these sorts of things.

Other examples of this:

* Allow easier reading with the /x switch
* Be careful with email addresses in strings on http://perl101.org/strings.html
* Create long strings with heredocs on http://perl101.org/strings.html
* Combine hashes with list assignment on http://perl101.org/hashes.html
* Subroutines have no argument checking on http://perl101.org/subroutines.html

These are all things that experienced Perl devs just know, but somebody coming to Perl green, maybe just picking up syntax from random Googling, wouldn't know.

**Comment by GeekRuthie** [comment]
Absolutely--yes, there is room for some Zero-to-Perl content, but there's also a lot of need, in my head-canon at least, for that sort of thing, as well as for content that answers the need of "I don't remember exactly the way you do <x> because I haven't done that in a while," which is something *I* have needed, even after all these years.  

(Yes, some of that is in perldoc.  Yes, some of that is on other sites as well. No, not all of that content is well-structured or intuitive enough. That's why curating a collection of multiple solutions is a good idea, IMO.  TIMTOWTDI.)

**Comment by tmetro** [comment]
@GeekRuthie wrote:
> the site should be forever free of commercial influence.
I'm aware of a sensitivity to advertising in an open source community, which is why I disclosed that intention up front so @petdance could make an informed decision.

>learners have different styles, and a piece of content that works as a teaching tool for one student, may not for another.
Definitely and coming at it from that perspective could be a good approach, as long as you figure out what that different style is and your contributors are aware of it.

@petdance wrote:
>wasn't that it would be a place for people to learn Perl from scratch.
I think Minimum Viable Perl does a decent job of that. It's designed to work for those who already know programming concepts, and just need to learn Perl. (There's yet another niche to be filled with a (larger scope) tutorial that teaches programming using Perl, assuming no prior programming knowledge. A site or video likely exists for that.)

But it sounds like...
>learned just enough syntax to start creating code, but who didn't know what they didn't know.
...perl101 would be a good follow-on after someone has completed MVP or equivalent.
Maybe it's actually perl201? :-) 

>These are all things that experienced Perl devs just know, but somebody coming to Perl green, maybe just picking up syntax from random Googling, wouldn't know.
The examples remind me of the sort of stuff that is/was in the Perl FAQs.

That sounds like a well articulated vision. As long as the site home page explains that, and puts the site into the context of the other available tutorial sites, pointing people elsewhere for the MVP-like content, and so forth, then both readers and contributors know what they'll get from perl101 different from the other sites.
